from Mapa import Mapa

mapa = Mapa()
mapa.agregar("Java", "Lenguaje de programación especializado en Programación Orientada a Objetos")
mapa.agregar("Python", "Lenguaje de programación de alto nivel")
mapa.agregar("PHP", "Lenguaje de programación orientado a objetos y de comunicación con el servidor")
mapa.agregar("C++", "Lenguaje de programación de alto nivel")
mapa.agregar("C#", "Lenguaje de programación orientado a objetos, evolución de C++")
mapa.agregar("JavaScript", "Lenguaje de programación orientado a objetos y orientado a páginas Web")
mapa.agregar("Ruby", "Lenguaje de programación orientado a objetos")
mapa.agregar("C", "Lenguaje de programación orientado a objetos")
mapa.imprimir()
print("\n")
input("PRESIONE UNA TECLA PARA ENTER/INTRO PARA CONTINUAR...")
print("\n")

print("****************************************************************************************************************")
print("\t\t*Buscar una palabra en el mapa*")
print("\t\t----Palabra a buscar = 'Java'----")
buscar = "Java"
busqueda = mapa.buscar("Java")
if busqueda != None:
    print("\t\tLa palabra "+buscar+" se encuentra en el mapa")
    print("****************************************************************************************************************")
    print(buscar+": "+busqueda)
else:
    print("\t\tLa palabra "+buscar+" no se encuentra en el mapa")
print("\n")
input("PRESIONE UNA TECLA PARA ENTER/INTRO PARA CONTINUAR...")
print("\n")

print("****************************************************************************************************************")
print("\t\t*ORDENANDO EL MAPA EN ORDEN ALFABETICO*")
mapa.ordenar()
mapa.imprimir()
print("\n")
input("PRESIONE UNA TECLA PARA ENTER/INTRO PARA CONTINUAR...")
print("\n")

print("****************************************************************************************************************")
print("\t\t*DESORDENANDO EL MAPA*")
mapa.desordenar()
mapa.imprimir()
print("\n")
input("PRESIONE UNA TECLA PARA ENTER/INTRO PARA CONTINUAR...")
print("\n")

print("****************************************************************************************************************")
print("\t\t*ELIMINAR UNA PALABRA DEL MAPA*")
print("\t\t----Palabra a eliminar = 'PHP'----")
eliminar = "PHP"
mapa.eliminar(eliminar)
mapa.imprimir()
print("\n")
input("PRESIONE UNA TECLA PARA ENTER/INTRO PARA CONTINUAR...")
print("\n")

print("****************************************************************************************************************")
print("\t\t*INSERTANDO PALABRAS Y SIGNIFICADO EN EL MAPA*")
print("\t\t----Palabra a insertar = 'GO'----")
print("\t----Significado de la palabra = 'Lenguaje auspiciado por Google'----")
insertar = "GO"
significado = "Lenguaje auspiciado por Google"
mapa.insertar(insertar, significado)
mapa.imprimir()
print("\n")
input("PRESIONE UNA TECLA PARA ENTER/INTRO PARA CONTINUAR...")
print("\n")

print("****************************************************************************************************************")
print("\t\t*RECORRIDO DE INICIO A FIN*")
print("****************************************************************************************************************")
mapa.recorridoInicioFin()
print("\n")
input("PRESIONE UNA TECLA PARA ENTER/INTRO PARA CONTINUAR...")
print("\n")

print("****************************************************************************************************************")
print("\t\t*RECORRIDO DE FIN A INICIO*")
print("****************************************************************************************************************")
mapa.recorridoFinInicio()
print("\n")
input("PRESIONE UNA TECLA PARA ENTER/INTRO PARA CONTINUAR...")
print("\n")