package Principal;

import Ejercicios.E1;
import Ejercicios.E2;
import Ejercicios.E3;
import Ejercicios.E4;
import Ejercicios.E5;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hacke
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraMenu = new javax.swing.JMenuBar();
        abrirMenu = new javax.swing.JMenu();
        investigacion = new javax.swing.JMenuItem();
        ejercicio1 = new javax.swing.JMenuItem();
        ejercicio2 = new javax.swing.JMenuItem();
        ejercicio3 = new javax.swing.JMenuItem();
        ejercicio4 = new javax.swing.JMenuItem();
        ejercicio5 = new javax.swing.JMenuItem();
        datosEstudianteMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Actividad de Aprendizaje Unidad 1");

        abrirMenu.setText("Abrir");

        investigacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pdf.png"))); // NOI18N
        investigacion.setText("Investigación");
        investigacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                investigacionActionPerformed(evt);
            }
        });
        abrirMenu.add(investigacion);

        ejercicio1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ejercicio1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/java24.png"))); // NOI18N
        ejercicio1.setText("Ejercicio 1");
        ejercicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejercicio1ActionPerformed(evt);
            }
        });
        abrirMenu.add(ejercicio1);

        ejercicio2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ejercicio2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/java24.png"))); // NOI18N
        ejercicio2.setText("Ejercicio 2");
        ejercicio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejercicio2ActionPerformed(evt);
            }
        });
        abrirMenu.add(ejercicio2);

        ejercicio3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ejercicio3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/java24.png"))); // NOI18N
        ejercicio3.setText("Ejercicio 3");
        ejercicio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejercicio3ActionPerformed(evt);
            }
        });
        abrirMenu.add(ejercicio3);

        ejercicio4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ejercicio4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/java24.png"))); // NOI18N
        ejercicio4.setText("Ejercicio 4");
        ejercicio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejercicio4ActionPerformed(evt);
            }
        });
        abrirMenu.add(ejercicio4);

        ejercicio5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ejercicio5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/java24.png"))); // NOI18N
        ejercicio5.setText("Ejercicio 5");
        ejercicio5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejercicio5ActionPerformed(evt);
            }
        });
        abrirMenu.add(ejercicio5);

        barraMenu.add(abrirMenu);

        datosEstudianteMenu.setText("Datos estudiante");
        barraMenu.add(datosEstudianteMenu);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void investigacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_investigacionActionPerformed
        File archivo = new File("src/documents/AAU1.pdf");
        try {
            Desktop.getDesktop().open(archivo);
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_investigacionActionPerformed

    private void ejercicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejercicio1ActionPerformed
        E1 ejercicio1 = new E1(this, rootPaneCheckingEnabled);
        ejercicio1.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_ejercicio1ActionPerformed

    private void ejercicio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejercicio2ActionPerformed
        E2 ejercicio2 = new E2(this, rootPaneCheckingEnabled);
        ejercicio2.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_ejercicio2ActionPerformed

    private void ejercicio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejercicio3ActionPerformed
        E3 ejercicio3 = new E3(this, rootPaneCheckingEnabled);
        ejercicio3.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_ejercicio3ActionPerformed

    private void ejercicio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejercicio4ActionPerformed
        E4 ejercicio4 = new E4(this, rootPaneCheckingEnabled);
        ejercicio4.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_ejercicio4ActionPerformed

    private void ejercicio5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejercicio5ActionPerformed
        E5 ejercicio5 = new E5(this, rootPaneCheckingEnabled);
        ejercicio5.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_ejercicio5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu abrirMenu;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenu datosEstudianteMenu;
    private javax.swing.JMenuItem ejercicio1;
    private javax.swing.JMenuItem ejercicio2;
    private javax.swing.JMenuItem ejercicio3;
    private javax.swing.JMenuItem ejercicio4;
    private javax.swing.JMenuItem ejercicio5;
    private javax.swing.JMenuItem investigacion;
    // End of variables declaration//GEN-END:variables
}
