package Principal;

import EP1U1.Ej11;
import EP1U1.Ej12;
import EP1U1.Ej13;
import EP1U1.Ej14;
import EP1U1.Ej15;
import EP2U1.Ej21;
import EP2U1.Ej22;
import EP2U1.Ej23;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hacke
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraMenu = new javax.swing.JMenuBar();
        ejerciciosPropuestos1 = new javax.swing.JMenu();
        investigacion = new javax.swing.JMenuItem();
        ejercicio1 = new javax.swing.JMenuItem();
        ejercicio2 = new javax.swing.JMenuItem();
        ejercicio3 = new javax.swing.JMenuItem();
        ejercicio4 = new javax.swing.JMenuItem();
        ejercicio5 = new javax.swing.JMenuItem();
        ejerciciosPropuestos2 = new javax.swing.JMenu();
        investigacion2 = new javax.swing.JMenuItem();
        ejercicio21 = new javax.swing.JMenuItem();
        ejercicio22 = new javax.swing.JMenuItem();
        ejercicio23 = new javax.swing.JMenuItem();
        ejercicio24 = new javax.swing.JMenuItem();
        infoSobreDesarrolladorMenu = new javax.swing.JMenu();
        info = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Actividad de Aprendizaje Unidad 1");

        ejerciciosPropuestos1.setText("Ejercicios propuestos 1");
        ejerciciosPropuestos1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        investigacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pdf.png"))); // NOI18N
        investigacion.setText("Investigación");
        investigacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                investigacionActionPerformed(evt);
            }
        });
        ejerciciosPropuestos1.add(investigacion);

        ejercicio1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ejercicio1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/java24.png"))); // NOI18N
        ejercicio1.setText("Ejercicio 1");
        ejercicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejercicio1ActionPerformed(evt);
            }
        });
        ejerciciosPropuestos1.add(ejercicio1);

        ejercicio2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ejercicio2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/java24.png"))); // NOI18N
        ejercicio2.setText("Ejercicio 2");
        ejercicio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejercicio2ActionPerformed(evt);
            }
        });
        ejerciciosPropuestos1.add(ejercicio2);

        ejercicio3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ejercicio3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/java24.png"))); // NOI18N
        ejercicio3.setText("Ejercicio 3");
        ejercicio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejercicio3ActionPerformed(evt);
            }
        });
        ejerciciosPropuestos1.add(ejercicio3);

        ejercicio4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ejercicio4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/java24.png"))); // NOI18N
        ejercicio4.setText("Ejercicio 4");
        ejercicio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejercicio4ActionPerformed(evt);
            }
        });
        ejerciciosPropuestos1.add(ejercicio4);

        ejercicio5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ejercicio5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/java24.png"))); // NOI18N
        ejercicio5.setText("Ejercicio 5");
        ejercicio5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejercicio5ActionPerformed(evt);
            }
        });
        ejerciciosPropuestos1.add(ejercicio5);

        barraMenu.add(ejerciciosPropuestos1);

        ejerciciosPropuestos2.setText("Ejercicios propuestos 2");
        ejerciciosPropuestos2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        investigacion2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pdf.png"))); // NOI18N
        investigacion2.setText("Investigación");
        investigacion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                investigacion2ActionPerformed(evt);
            }
        });
        ejerciciosPropuestos2.add(investigacion2);

        ejercicio21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ejercicio21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/java24.png"))); // NOI18N
        ejercicio21.setText("Ejercicio 1");
        ejercicio21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejercicio21ActionPerformed(evt);
            }
        });
        ejerciciosPropuestos2.add(ejercicio21);

        ejercicio22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ejercicio22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/java24.png"))); // NOI18N
        ejercicio22.setText("Ejercicio 2");
        ejercicio22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejercicio22ActionPerformed(evt);
            }
        });
        ejerciciosPropuestos2.add(ejercicio22);

        ejercicio23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ejercicio23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/java24.png"))); // NOI18N
        ejercicio23.setText("Ejercicio 3");
        ejercicio23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejercicio23ActionPerformed(evt);
            }
        });
        ejerciciosPropuestos2.add(ejercicio23);

        ejercicio24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ejercicio24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/java24.png"))); // NOI18N
        ejercicio24.setText("Ejercicio 4");
        ejercicio24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejercicio24ActionPerformed(evt);
            }
        });
        ejerciciosPropuestos2.add(ejercicio24);

        barraMenu.add(ejerciciosPropuestos2);

        infoSobreDesarrolladorMenu.setText("Acerca de...");

        info.setText("Desarrollador info");
        info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoActionPerformed(evt);
            }
        });
        infoSobreDesarrolladorMenu.add(info);

        barraMenu.add(infoSobreDesarrolladorMenu);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void investigacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_investigacionActionPerformed
        File archivo = new File("src/documents/AAU1-1.pdf");
        try {
            Desktop.getDesktop().open(archivo);
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_investigacionActionPerformed

    private void ejercicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejercicio1ActionPerformed
        Ej11 ejercicio1 = new Ej11(this, rootPaneCheckingEnabled);
        ejercicio1.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_ejercicio1ActionPerformed

    private void ejercicio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejercicio2ActionPerformed
        Ej12 ejercicio2 = new Ej12(this, rootPaneCheckingEnabled);
        ejercicio2.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_ejercicio2ActionPerformed

    private void ejercicio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejercicio3ActionPerformed
        Ej13 ejercicio3 = new Ej13(this, rootPaneCheckingEnabled);
        ejercicio3.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_ejercicio3ActionPerformed

    private void ejercicio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejercicio4ActionPerformed
        Ej14 ejercicio4 = new Ej14(this, rootPaneCheckingEnabled);
        ejercicio4.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_ejercicio4ActionPerformed

    private void ejercicio5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejercicio5ActionPerformed
        Ej15 ejercicio5 = new Ej15(this, rootPaneCheckingEnabled);
        ejercicio5.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_ejercicio5ActionPerformed

    private void infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoActionPerformed
        About estudiante = new About(this, rootPaneCheckingEnabled);
        estudiante.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_infoActionPerformed

    private void investigacion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_investigacion2ActionPerformed
        File archivo = new File("src/documents/AAU1-2.pdf");
        try {
            Desktop.getDesktop().open(archivo);
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_investigacion2ActionPerformed

    private void ejercicio21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejercicio21ActionPerformed
        Ej21 ejercicio21 = new Ej21(this, rootPaneCheckingEnabled);
        ejercicio21.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_ejercicio21ActionPerformed

    private void ejercicio22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejercicio22ActionPerformed
        Ej22 ejercicio22 = new Ej22(this, rootPaneCheckingEnabled);
        ejercicio22.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_ejercicio22ActionPerformed

    private void ejercicio23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejercicio23ActionPerformed
        Ej23 ejercicio23 = new Ej23(this, rootPaneCheckingEnabled);
        ejercicio23.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_ejercicio23ActionPerformed

    private void ejercicio24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejercicio24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ejercicio24ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem ejercicio1;
    private javax.swing.JMenuItem ejercicio2;
    private javax.swing.JMenuItem ejercicio21;
    private javax.swing.JMenuItem ejercicio22;
    private javax.swing.JMenuItem ejercicio23;
    private javax.swing.JMenuItem ejercicio24;
    private javax.swing.JMenuItem ejercicio3;
    private javax.swing.JMenuItem ejercicio4;
    private javax.swing.JMenuItem ejercicio5;
    private javax.swing.JMenu ejerciciosPropuestos1;
    private javax.swing.JMenu ejerciciosPropuestos2;
    private javax.swing.JMenuItem info;
    private javax.swing.JMenu infoSobreDesarrolladorMenu;
    private javax.swing.JMenuItem investigacion;
    private javax.swing.JMenuItem investigacion2;
    // End of variables declaration//GEN-END:variables
}
