/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EP2U1;

import Control.ValidaEntrada;
import Enunciados.E21;
import java.util.InputMismatchException;
import java.util.Scanner;

/**
 *
 * @author TECNOLOGIA GC
 */
public class Ej21 extends javax.swing.JDialog {

    /**
     * Creates new form E2
     */
    private ValidaEntrada validador;
    private Scanner key;
    
    public Ej21(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        validador = new ValidaEntrada();
        key = new Scanner(System.in);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        enunciado3 = new javax.swing.JButton();
        calcularBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Ejercicios propuestos 2");

        enunciado3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        enunciado3.setText("Ver enunciado");
        enunciado3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enunciado3ActionPerformed(evt);
            }
        });

        calcularBtn.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        calcularBtn.setText("Iniciar consola");
        calcularBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Ejercicio 1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(calcularBtn)
                            .addComponent(enunciado3))))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enunciado3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calcularBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enunciado3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enunciado3ActionPerformed
        E21 ejercicio1 = new E21(null, rootPaneCheckingEnabled);
        ejercicio1.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_enunciado3ActionPerformed

    public int menu(){
        int op = 0;
        try{
            System.out.print("********CALCULADORA MENU********"
                    + "\n1.SUMAR"
                    + "\n2.RESTAR"
                    + "\n3.MULTIPLICAR"
                    + "\n4.DIVIDIR"
                    + "\n5.SALIR"
                    + "\n********CALCULADORA MENU********"
                    + "\nESCOJA UNA OPERACION A REALIZAR: ");
            op = key.nextInt();
        }catch(NumberFormatException | InputMismatchException err){
            System.out.println("OCION INVALIDA");
        }
        return op;
    }
    
    private void calcularBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularBtnActionPerformed
        double dato1, dato2;
        switch(menu()){
            case 1:
                System.out.println("Dato 1: ");
                dato1 = key.nextDouble();
                
                System.out.println("Dato 2: ");
                dato2 = key.nextDouble();
                
                System.out.println("Resultado = "+(dato1+dato2));
                calcularBtnActionPerformed(evt);
                break;
                
            case 2:
                System.out.println("Dato 1: ");
                dato1 = key.nextDouble();
                
                System.out.println("Dato 2: ");
                dato2 = key.nextDouble();
                
                System.out.println("Resultado = "+(dato1-dato2));
                calcularBtnActionPerformed(evt);
                break;
                
            case 3:
                System.out.println("Dato 1: ");
                dato1 = key.nextDouble();
                
                System.out.println("Dato 2: ");
                dato2 = key.nextDouble();
                
                System.out.println("Resultado = "+(dato1*dato2));
                calcularBtnActionPerformed(evt);
                break;
                
            case 4:
                System.out.println("Dato 1: ");
                dato1 = key.nextDouble();
                
                System.out.println("Dato 2: ");
                dato2 = key.nextDouble();
                
                if(dato2 != 0)
                    System.out.println("Resultado = "+(dato1/dato2));
                else
                    System.out.println("La división por cero no está definida");
                calcularBtnActionPerformed(evt);
                break;
                
            case 5:
                System.out.println("Gracias por usar nuestra Calculadora, Bye");
                dispose();
                break;
        }
    }//GEN-LAST:event_calcularBtnActionPerformed
                 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ej21.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ej21.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ej21.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ej21.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Ej21 dialog = new Ej21(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcularBtn;
    private javax.swing.JButton enunciado3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
