/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EP2U1;

import Control.ValidaEntrada;
import Enunciados.E24;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author TECNOLOGIA GC
 */
public class Ej24 extends javax.swing.JDialog {

    /**
     * Creates new form E2
     */
    private ValidaEntrada validador;
    private Gasolinera gasolinera;
    private ArrayList<Gasolinera> gasolineras;
    
    public Ej24(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        validador = new ValidaEntrada();
        gasolineras = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        enunciado5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        valorServicioTextField = new javax.swing.JTextField();
        calcularBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jornadaComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        agregarBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultadoTextArea = new javax.swing.JTextArea();
        claseServicioComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Ejercicios propuestos 2");

        enunciado5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        enunciado5.setText("Ver enunciado");
        enunciado5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enunciado5ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Jornada");

        valorServicioTextField.setToolTipText("");
        valorServicioTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                valorServicioTextFieldMouseClicked(evt);
            }
        });
        valorServicioTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                valorServicioTextFieldKeyTyped(evt);
            }
        });

        calcularBtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        calcularBtn.setText("Calcular");
        calcularBtn.setBorder(new javax.swing.border.MatteBorder(null));
        calcularBtn.setEnabled(false);
        calcularBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setLabelFor(resultadoTextArea);
        jLabel3.setText("Resultado");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Valor del servicio");

        jornadaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mañana", "Tarde" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Clase de servicio");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Ejercicio 4");

        agregarBtn.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        agregarBtn.setText("Agregar");
        agregarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBtnActionPerformed(evt);
            }
        });

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        resultadoTextArea.setEditable(false);
        resultadoTextArea.setColumns(20);
        resultadoTextArea.setLineWrap(true);
        resultadoTextArea.setRows(5);
        resultadoTextArea.setWrapStyleWord(true);
        jScrollPane2.setViewportView(resultadoTextArea);

        claseServicioComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(valorServicioTextField))
                            .addComponent(claseServicioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jornadaComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addComponent(agregarBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calcularBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(enunciado5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jLabel7)))
                        .addGap(52, 52, 52)))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(8, 8, 8)
                .addComponent(enunciado5)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jornadaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(claseServicioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valorServicioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(agregarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calcularBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enunciado5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enunciado5ActionPerformed
        E24 ejercicio4 = new E24(null, rootPaneCheckingEnabled);
        ejercicio4.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_enunciado5ActionPerformed

    private void calcularBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularBtnActionPerformed
        int contadorServicio1 = 0, contadorServicio2 = 0, contadorServicio3 = 0
                , contadorServicio4 = 0, contadorManana = 0, contadorTarde = 0;
        
        String servicioMasPrestado = "", jornadaMasUsada = "";
        
        for(int i =0; i<gasolineras.size(); i++){
            switch(gasolineras.get(i).getClaseServicio()){
                case 1:
                    contadorServicio1++;
                    break;
                    
                case 2:
                    contadorServicio2++;
                    break;
                    
                case 3:
                    contadorServicio3++;
                    break;
                    
                case 4:
                    contadorServicio4++;
                    break;
            }
        }
        
        if(contadorServicio1 > contadorServicio2 
                && contadorServicio1 > contadorServicio3 
                && contadorServicio1 > contadorServicio4){
            servicioMasPrestado = "Servicio 1";
            
            for(int i = 0; i<gasolineras.size(); i++){
                if(gasolineras.get(i).getClaseServicio() == 1){
                    if(gasolineras.get(i).getJornada().toLowerCase().equals("mañana")){
                        contadorManana++;
                    }else{
                        contadorTarde++;
                    }
                }
            }
            
            if(contadorManana > contadorTarde){
                jornadaMasUsada = "Mañana";
            }else{
                jornadaMasUsada = "Tarde";
            }
            
        }else if(contadorServicio2 > contadorServicio1 
                && contadorServicio2 > contadorServicio3 
                && contadorServicio2 > contadorServicio4){
            servicioMasPrestado = "Servicio 2";
            
            for(int i = 0; i<gasolineras.size(); i++){
                if(gasolineras.get(i).getClaseServicio() == 2){
                    if(gasolineras.get(i).getJornada().toLowerCase().equals("mañana")){
                        contadorManana++;
                    }else{
                        contadorTarde++;
                    }
                }
            }
            
            if(contadorManana > contadorTarde){
                jornadaMasUsada = "Mañana";
            }else{
                jornadaMasUsada = "Tarde";
            }
        }else if(contadorServicio3 > contadorServicio1 
                && contadorServicio3 > contadorServicio2 
                && contadorServicio3 > contadorServicio4){
            servicioMasPrestado = "Servicio 3";
            
            for(int i = 0; i<gasolineras.size(); i++){
                if(gasolineras.get(i).getClaseServicio() == 3){
                    if(gasolineras.get(i).getJornada().toLowerCase().equals("mañana")){
                        contadorManana++;
                    }else{
                        contadorTarde++;
                    }
                }
            }
            
            if(contadorManana > contadorTarde){
                jornadaMasUsada = "Mañana";
            }else{
                jornadaMasUsada = "Tarde";
            }
        }else if(contadorServicio4 > contadorServicio1 
                && contadorServicio4 > contadorServicio2 
                && contadorServicio4 > contadorServicio3){
            servicioMasPrestado = "Servicio 4";
            
            for(int i = 0; i<gasolineras.size(); i++){
                if(gasolineras.get(i).getClaseServicio() == 4){
                    if(gasolineras.get(i).getJornada().toLowerCase().equals("mañana")){
                        contadorManana++;
                    }else{
                        contadorTarde++;
                    }
                }
            }
            
            if(contadorManana > contadorTarde){
                jornadaMasUsada = "Mañana";
            }else{
                jornadaMasUsada = "Tarde";
            }
        }
        
        //IMPRIME EL VALOR DE CADA SERVICIO
        //IMPRIME CANTIDAD DE VECES DE CADA SERVICIO
        for(int i = 0; i<gasolineras.size(); i++){
            switch(gasolineras.get(i).getClaseServicio()){
                case 1:
                    resultadoTextArea.append("Valor servicio 1: $"
                            +gasolineras.get(i).getValorServicio()
                            +"\nCantidad: "+contadorServicio1+"\n");
                    break;
                    
                case 2:
                    resultadoTextArea.append("Valor servicio 2: $"
                            +gasolineras.get(i).getValorServicio()
                            +"\nCantidad: "+contadorServicio2+"\n");
                    break;
                    
                case 3:
                    resultadoTextArea.append("Valor servicio 3: $"
                            +gasolineras.get(i).getValorServicio()
                            +"\nCantidad: "+contadorServicio3+"\n");
                    break;
                    
                case 4:
                    resultadoTextArea.append("Valor servicio 4: $"
                            +gasolineras.get(i).getValorServicio()
                            +"\nCantidad: "+contadorServicio4+"\n");
                    break;
            }
        }
        
        resultadoTextArea.append("************************************"
                + "\nEl servicio más prestado fue el *"
                +servicioMasPrestado.toLowerCase()+"*"+
                "\nEn la jornada de la *"+jornadaMasUsada.toLowerCase()+"*");
    }//GEN-LAST:event_calcularBtnActionPerformed

    private void valorServicioTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorServicioTextFieldKeyTyped
        validador.validaNumerosDouble(evt);
        if(valorServicioTextField.getText().length() > 8){
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }            
    }//GEN-LAST:event_valorServicioTextFieldKeyTyped

    private void agregarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBtnActionPerformed
        if(valorServicioTextField.getText().isEmpty()){
            valorServicioTextField.setText("$0");
            JOptionPane.showMessageDialog(null, "POR FAVOR LLENE LOS CAMPOS"
                    ,"ADVERTENCIA",JOptionPane.ERROR_MESSAGE);
        }else{
            int claseServicio = Integer.valueOf(claseServicioComboBox.getSelectedItem().toString());
            double valorServicio = Double.valueOf(valorServicioTextField.getText());
            gasolinera = new Gasolinera(claseServicio
                , jornadaComboBox.getSelectedItem().toString().toLowerCase()
                , valorServicio);
            gasolineras.add(gasolinera);
            calcularBtn.setEnabled(true);
        }
    }//GEN-LAST:event_agregarBtnActionPerformed

    private void valorServicioTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valorServicioTextFieldMouseClicked
        valorServicioTextField.setText("");
    }//GEN-LAST:event_valorServicioTextFieldMouseClicked
                 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ej24.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ej24.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ej24.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ej24.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Ej24 dialog = new Ej24(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarBtn;
    private javax.swing.JButton calcularBtn;
    private javax.swing.JComboBox<String> claseServicioComboBox;
    private javax.swing.JButton enunciado5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jornadaComboBox;
    private javax.swing.JTextArea resultadoTextArea;
    private javax.swing.JTextField valorServicioTextField;
    // End of variables declaration//GEN-END:variables
}
