/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EP1U1;

import Control.ValidaEntrada;
import Enunciados.E15;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author TECNOLOGIA GC
 */
public class Ej15 extends javax.swing.JDialog {

    /**
     * Creates new form E2
     */
    private ValidaEntrada validador;
    
    public Ej15(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        validador = new ValidaEntrada();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        enunciado5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        creditosTextField = new javax.swing.JTextField();
        calcularBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultadoTextArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tipoProgramaComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        promedioTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nombreEstudianteJTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Ejercicios propuestos 1");

        enunciado5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        enunciado5.setText("Ver enunciado");
        enunciado5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enunciado5ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Tipo de programa");

        creditosTextField.setToolTipText("");
        creditosTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                creditosTextFieldKeyTyped(evt);
            }
        });

        calcularBtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        calcularBtn.setText("Calcular");
        calcularBtn.setBorder(new javax.swing.border.MatteBorder(null));
        calcularBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularBtnActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        resultadoTextArea.setEditable(false);
        resultadoTextArea.setColumns(20);
        resultadoTextArea.setLineWrap(true);
        resultadoTextArea.setRows(5);
        resultadoTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(resultadoTextArea);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setLabelFor(resultadoTextArea);
        jLabel3.setText("Factura");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Cantidad de créditos");

        tipoProgramaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pregrado", "Postgrado" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Promedio");

        promedioTextField.setToolTipText("");
        promedioTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                promedioTextFieldKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Nombre de Estudiante");

        nombreEstudianteJTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombreEstudianteJTextFieldMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Ejercicio 5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(nombreEstudianteJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(tipoProgramaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(calcularBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(enunciado5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(promedioTextField))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(creditosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(8, 8, 8)
                .addComponent(enunciado5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoProgramaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreEstudianteJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(promedioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(creditosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(calcularBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enunciado5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enunciado5ActionPerformed
        E15 ejercicio5 = new E15(null, rootPaneCheckingEnabled);
        ejercicio5.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_enunciado5ActionPerformed

    private void calcularBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularBtnActionPerformed
        
        
        if(creditosTextField.getText().isEmpty() 
                || nombreEstudianteJTextField.getText().isEmpty() 
                || promedioTextField.getText().isEmpty()){
            creditosTextField.setText("1");
            nombreEstudianteJTextField.setText("SIN NOMBRE");
            promedioTextField.setText("0.0");
        }else{
            try{
                int descuento = 0;

                double promedio = Double.valueOf(promedioTextField.getText());
                int creditos = Integer.valueOf(creditosTextField.getText());
                int valorPagar = creditos*50000;

                switch(tipoProgramaComboBox.getSelectedItem().toString().toLowerCase()){
                    case "pregrado":
                        if(promedio >= 2.5){
                            resultadoTextArea.setText("El estudiante "
                                        +nombreEstudianteJTextField.getText()
                                        +" del programa de "
                                        +tipoProgramaComboBox.getSelectedItem().toString()
                                        +"\nDebe pagar"
                                        +"\n$"+validador.separadorDeMiles(valorPagar)
                                        +" -----> 0% de descuento");
                            if(promedio >= 4.0 && promedio < 4.5 ){
                                descuento = (int)(valorPagar*0.1);
                                valorPagar -= descuento;
                                resultadoTextArea.setText("El estudiante "
                                        +nombreEstudianteJTextField.getText()
                                        +" del programa de "
                                        +tipoProgramaComboBox.getSelectedItem().toString()
                                        +"\nDebe pagar"
                                        +"\n$"+validador.separadorDeMiles(valorPagar)
                                        +" -----> 10% de descuento");
                            }else if(promedio >= 4.5){
                                descuento = (int)(valorPagar*0.25);
                                valorPagar -= descuento;
                                resultadoTextArea.setText("El estudiante "
                                        +nombreEstudianteJTextField.getText()
                                        +" del programa de "
                                        +tipoProgramaComboBox.getSelectedItem().toString()
                                        +"\nDebe pagar"
                                        +"\n$"+validador.separadorDeMiles(valorPagar)
                                        +" -----> 25% de descuento");
                            }
                        }else{
                            JOptionPane.showMessageDialog(this, 
                                    "USTED NO PODRA MATRICULARSE", "LO SENTIMOS", 
                                    JOptionPane.ERROR_MESSAGE);
                        }
                        break;

                    case "postgrado":
                        valorPagar = creditos*300000;
                        if(promedio >= 4.5){
                            descuento = (int)(valorPagar*0.2);
                            valorPagar -= descuento;
                            resultadoTextArea.setText("El estudiante "
                                            +nombreEstudianteJTextField.getText()
                                            +" del programa de "
                                            +tipoProgramaComboBox.getSelectedItem().toString()
                                            +"\nDebe pagar"
                                            +"\n$"+validador.separadorDeMiles(valorPagar)
                                            +" -----> 20% de descuento");
                        }else{
                            resultadoTextArea.setText("El estudiante "
                                            +nombreEstudianteJTextField.getText()
                                            +" del programa de "
                                            +tipoProgramaComboBox.getSelectedItem().toString()
                                            +"\nDebe pagar"
                                            +"\n$"+validador.separadorDeMiles(valorPagar)
                                            +" -----> 0% de descuento");
                        }
                    break;
                }
            }catch(NumberFormatException err){
                JOptionPane.showMessageDialog(this, 
                            "DATO INVALIDO", "LO SENTIMOS", 
                            JOptionPane.ERROR_MESSAGE);
                creditosTextField.setText("1");
                nombreEstudianteJTextField.setText("SIN NOMBRE");
                promedioTextField.setText("0.0");
            }
        }
    }//GEN-LAST:event_calcularBtnActionPerformed

    private void creditosTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_creditosTextFieldKeyTyped
        validador.validaNumerosInt(evt);
        if(creditosTextField.getText().length() > 8){
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }            
    }//GEN-LAST:event_creditosTextFieldKeyTyped

    private void promedioTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_promedioTextFieldKeyTyped
        validador.validaNumerosInt(evt);
    }//GEN-LAST:event_promedioTextFieldKeyTyped

    private void nombreEstudianteJTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreEstudianteJTextFieldMouseClicked
        nombreEstudianteJTextField.setText("");
    }//GEN-LAST:event_nombreEstudianteJTextFieldMouseClicked
                 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ej15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ej15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ej15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ej15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Ej15 dialog = new Ej15(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcularBtn;
    private javax.swing.JTextField creditosTextField;
    private javax.swing.JButton enunciado5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombreEstudianteJTextField;
    private javax.swing.JTextField promedioTextField;
    private javax.swing.JTextArea resultadoTextArea;
    private javax.swing.JComboBox<String> tipoProgramaComboBox;
    // End of variables declaration//GEN-END:variables
}
